name: firebase_device_id_example
description: Demonstrates how to use the firebase_device_id plugin.

# This is an example project and should not ever be published
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 1.4.0

  firebase_device_id:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
